#!/bin/bash
echo 'Installing packages';

# NodeJS - https://github.com/joyent/node/wiki/installing-node.js-via-package-manager
sudo apt-get install -y curl
curl -sL https://deb.nodesource.com/setup | sudo bash -
sudo apt-get install -y nodejs

# postgreSQL - https://help.ubuntu.com/community/PostgreSQL
sudo apt-get install -y postgresql postgresql-contrib
echo '>> \password postgres'
sudo -u postgres psql postgres

# phpPgAdmin installation (dev only)
sudo apt-get install -y phppgadmin
